### ISSUE TITLE
2nd call to WORD-completion eats command line

### ISSUE THREAD

**Issue by Lompik** [Vifon/autocomplete-ALL-the-things#11]
Here's a reproducible example on my machine:
    
    #Step1 
    $cat temp.txt
    comple1
    compl2
    noitelpomc34
    #Step 2
    $echo comp<C-M-/><Enter>
    compl2
    #Step 3
    $echo noi<C-M-/>
    # after calling WORD-complete the command line looks like this :
    $echcomple1

**Comment by Vifon** [comment]
I could not reproduce it. Can you provide some more information?

Does calling `perl:aAtt:undo` in the last step instead of `WORD-complete` erase the characters too?

**Comment by Lompik** [comment]
- In `Step 3`, when hitting the the `WORD-complete` key I see highligh showing on `comple1`.
 - Calling `perl:aTT:undo` in `Step 2` between `<C-M-/>` and `Enter`
 - Calling `perl:aTT:undo` in `Step 3` before `<C-M-/>` erase the characters too

The only tweak i did in source file was to use `$char_class_before      = '\b';` instead of "\s" for the `WORD-complete`. Is it reproducible with that tweak ?

**Comment by Vifon** [comment]
It seems `$self->{last_word}` is not resetting correctly. And it is done in the `leave()` function called from `conditional_leave()`. I still can't reproduce it, sadly. You could try to add a few `warn` statements to see what is being evaluated (and when) and what is not. Run urxvt from a terminal (even from another urxvt) and the output from warns should be there.

**Comment by Lompik** [comment]
Thanks !

it seems like `conditional_leave`  never enters the if confition as `$event->{'state'}` is  always >2 (ie in the 16..25 range) . I'm not sure where that variable comes from though.

**Comment by Vifon** [comment]
Maybe @seletskiy will be able to help, as he was the one that added this check. All I know about this variable is what he has described in this pull request: #9.

If you use urxvt pre-9.21, you may try using the older plugin version.

**Comment by Lompik** [comment]
Alright so this the values for the `event->{'state'}` : 
    
    # state bitmask: Shift = 1, Ctrl = 4, Alt = 8

However the issue is not the if condition as I thought since when I  hit `Enter` in Step 2, `conditional_leave` is not called ...

    rxvt-unicode (urxvt) v9.21 - released: 2014-12-31
    options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
    URxvt.perl-ext-common:      readline,matcher,selection-to-clipboard,keyboard-select,clipboard,autocomplete-ALL-the-things

**Comment by seletskiy** [comment]
@Lompik: do you have secondary keyboard layout? If so, then `state` value can depends on what keyboard layout is now active.

**Comment by Lompik** [comment]
https://github.com/seletskiy I have a modified xmodmap, I disabled caps-lock and move Control to caps . But not sure what you mean by secondary keyboard layout. It's probably this issue affects only me.

**Comment by seletskiy** [comment]
@Lompik: according to `/usr/include/X11/X.h` mask `16 = 1 << 4` stands for `Mod2`. `Mod2` is a NumLock by default, check NumLock state, then.

**Comment by Lompik** [comment]
@seletskiy you're right. Disabling numlock gets me the Shift = 1, Ctrl = 4, Alt = 8 values as initially expected. Are you guys not using Numlock ?

**Comment by Vifon** [comment]
Makes sense. Thanks a lot, guys. I'll fix it when I get back from work. I was going to rewrite that part anyway (there are issues with using ctrl/alt+something right after using the completion).

> Are you guys not using Numlock?

Not really. I don't even have a numpad.
