### ISSUE TITLE
Only map aAtt:undo when in completion mode

### ISSUE THREAD

**Issue by Ram-Z** [Vifon/autocomplete-ALL-the-things#12]
I'd like to map `perl:aAtt:undo` to <kbd>Esc</kbd> but obviously if I do `URxvt.keysym.Escape: perl:aAtt:undo`, I will not be able to use <kbd>Esc</kbd> anymore for anything else.

Do you think there is a way to do this? I fear not.

**Comment by Vifon** [comment]
There is no way to do this with the keybinding mechanism of urxvt but it's trivial to handle it in the `key_press` hook. I've hardcoded <kbd>Esc</kbd> because it just makes sense.

**Comment by Ram-Z** [comment]
Cool, works like a charm. Thanks
