### ISSUE TITLE
What is the font used in the demo gif?

### ISSUE THREAD

**Issue by 97-109-107** [Vifon/autocomplete-ALL-the-things#19]
Nobody so far was able to recognize this font. What is this weird travesty of a font that you use in the screencast? Xresources entries would be very welcome as well.

Thanks!

**Comment by Vifon** [comment]
These screencasts were recorded by @seletskiy, he should be able to answer your questions.

**Comment by 97-109-107** [comment]
Thanks, it seems to have been his own [**Monaco**](https://github.com/seletskiy/monaco-font/tree/8a875d4c9b1ecead5b95bde7f6230d7ba1d92233)

**Comment by seletskiy** [comment]
@97-109-107: Yep, it's my own font.
