### ISSUE TITLE
Eager completion for fuzzy complete

### ISSUE THREAD

**Issue by amosbird** [Vifon/autocomplete-ALL-the-things#23]
Hi, can I make `/po` match `/etc/yum.repos.d/CentOS-SCLo-scl.repo` instead of `/etc/yum.repo` ?

**Comment by Vifon** [comment]
It should be possible with a new completer.
A quick and dirty solution: make a copy of the `suffix-complete` completer ([these lines][1]), rename it and set `$char_class_before` to `\s` instead of `\S`. Then use your new completer. You might want to experiment with various sets of options but I've tested this one just now and it worked.

[1]: https://github.com/Vifon/autocomplete-ALL-the-things/blob/5f9e3d9e997c39dbda9c37080ab596733ee52623/autocomplete-ALL-the-things#L98-L104

Tell me if you need further assistance or if I may close the issue (or close it yourself).

**Comment by amosbird** [comment]
Thanks! Um but it doesn't work if there are spaces between completion candidates. Can I make fuzzy-complete to have such eager behavior?

**Comment by Vifon** [comment]
Yes, it should work with `fuzzy-complete` too but I didn't check it. It might be tricky to find the right combination of regexps that won't be too greedy.

What I usually do is abort the completion and add another occurrence of the last part I typed, i.e. `/po` becomes `/popo`.

**Comment by amosbird** [comment]
ah, good point. I'll use that trick :smile: . Thanks!  BTW, can I have empty string trigger completions for every space separated items?  Use case `pdfcrop /path/to/file /path/to/file` . After typing the first path entry, I'd like to auto complete the second one using just one call of fuzzy-complete without any inputs.

**Comment by Vifon** [comment]
You would need some special character to mark where to stop searching for the text supplied by the user. The completion needs to know what to consider an input. `'fuzzy-complete'` takes all characters before the cursor matching `\S` (all non-whitespace characters), `fuzzy-word-complete` uses `[-\w]` (every "word character" and additionally a hyphen). In your case we would need to also read the whitespace characters but then we have no character to stop at unless we add one artificially, for example you could add a dollar sign before your input and then probably remove it manually. In general, `$char_class_to_complete` is the variable you'd need to tinker with.

I hope to rewrite this plugin at some point to make such modifications easier but it's tough to estimate when I'll have the time to do so.

**Comment by amosbird** [comment]
> 'fuzzy-complete' takes all characters before the cursor matching \S (all non-whitespace characters)

Can we just have a special case for empty inputs?

**Comment by blueyed** [comment]
@amosbird 
btw: you can also use `pdfcrop /path/to/file{,.new}` directly.

**Comment by amosbird** [comment]
@blueyed thanks. Um i meant to do in place cropping.

**Comment by blueyed** [comment]
Then `pdfcrop /path/to/file{,}`, or `pdfcrop /path/to/file !#$`.. ;) - but enough for the offtopic.

**Comment by Vifon** [comment]
@amosbird What do you mean by empty inputs?

**Comment by amosbird** [comment]
I mean that all characters before the cursor matching \S is empty

**Comment by amosbird** [comment]
It's like if I input nothing and start triggering completion, it should match something like ".*"

**Comment by Vifon** [comment]
What should it complete in such case? Every single whole line?

**Comment by amosbird** [comment]
no, every single items separated by spaces

**Comment by Vifon** [comment]
Hm, I like this idea. I'll keep it in mind when rewriting the plugin.
