### ISSUE TITLE
Disappearing highlights

### ISSUE THREAD

**Issue by Vifon** [Vifon/autocomplete-ALL-the-things#8]
Sometimes the match highlights are disappearing just after they appear. I've been able to reproduce it on the same text over and over again but it was at my workplace so I can't diagnose it properly. I've not encountered it at home.

If someone has any idea what could be the cause or any hint, please give me a hand.

**Comment by blueyed** [comment]
For me they disappear because of the blinking cursor already.

Removing the `$self->enable(refresh_begin => \&clear_highlight);` seems to work around that - in case that this is not intentional (by now)?!

**Comment by Vifon** [comment]
It may not be *the* reason but you're right, the highlight is disappearing when the cursor is blinking. I never use the blinking cursor so I didn't notice.

The line you mentioned seems to be redundant considering [these lines][1]. I'll remove it and see what will happen during the next week or so. The hook hell at its best... So far it seems to be working fine and indeed fixes the issue with the blinking cursor.

[1]: https://github.com/Vifon/autocomplete-ALL-the-things/blob/70e828bebb4137e893a3209b077c0d7771ec476e/autocomplete-ALL-the-things#L230-L232

Thanks a lot!
